version: "3.8"

services:
    frontend:
        image: roeeyn/challenge_4_frontend
        ports:
          - "80:80"
        environment:
          # Change this for the publicly available url
            - BACKEND_HOST=http://backend:5000 
    backend:
        restart: always
        depends_on: 
            - db
        image: roeeyn/challenge_4_backend
        environment:
            - DB_PSWD=iamnotgroot
            - DB_HOST=db
        ports:
          # The backend needs to be publicly available
            - "5000:5000" 
    db:
        image: roeeyn/challenge_4_db
        restart: always
        #ports:
            # - "3306:3306"
        environment: 
            - MYSQL_ROOT_PASSWORD=iamgroot
